#if !canImport(ObjectiveC)
import XCTest

extension AccessorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccessorsTests = [
        ("testArray", testArray),
        ("testBinary", testBinary),
        ("testBool", testBool),
        ("testConversions", testConversions),
        ("testDictionary", testDictionary),
        ("testDouble", testDouble),
        ("testExtended", testExtended),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testString", testString),
        ("testUInt", testUInt),
    ]
}

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testDecodeArray16", testDecodeArray16),
        ("testDecodeArray32", testDecodeArray32),
        ("testDecodeFixarray", testDecodeFixarray),
        ("testEmptyArray", testEmptyArray),
        ("testEncodeArray16", testEncodeArray16),
        ("testEncodeArray32", testEncodeArray32),
        ("testEncodeFixArray", testEncodeFixArray),
        ("testFixArraySize", testFixArraySize),
    ]
}

extension BinaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryTests = [
        ("testDecodeBin16", testDecodeBin16),
        ("testDecodeBin32", testDecodeBin32),
        ("testDecodeBin8", testDecodeBin8),
        ("testEmptyBinary", testEmptyBinary),
        ("testEncodeBin16", testEncodeBin16),
        ("testEncodeBin32", testEncodeBin32),
        ("testEncodeBin8", testEncodeBin8),
    ]
}

extension BoolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoolTests = [
        ("testDecodeBoolFalse", testDecodeBoolFalse),
        ("testDecodeBoolTrue", testDecodeBoolTrue),
        ("testEncodeBoolFalse", testEncodeBoolFalse),
        ("testEncodeBoolTrue", testEncodeBoolTrue),
    ]
}

extension ConvenienceInitializersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConvenienceInitializersTests = [
        ("testArray", testArray),
        ("testBinary", testBinary),
        ("testBool", testBool),
        ("testDouble", testDouble),
        ("testExtended", testExtended),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testMap", testMap),
        ("testNil", testNil),
        ("testString", testString),
        ("testUInt", testUInt),
    ]
}

extension DecodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodeTests = [
        ("testArray", testArray),
        ("testBinary", testBinary),
        ("testBool", testBool),
        ("testDouble", testDouble),
        ("testExtended", testExtended),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testMap", testMap),
        ("testString", testString),
        ("testUInt", testUInt),
        ("testUIntMaxToInt", testUIntMaxToInt),
        ("testUIntToInt", testUIntToInt),
    ]
}

extension DescriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DescriptionTests = [
        ("testArrayDescription", testArrayDescription),
        ("testBinaryDescription", testBinaryDescription),
        ("testBoolDescription", testBoolDescription),
        ("testDoubleDescription", testDoubleDescription),
        ("testExtendedDescription", testExtendedDescription),
        ("testFloatDescription", testFloatDescription),
        ("testIntDescription", testIntDescription),
        ("testMapDescription", testMapDescription),
        ("testNilDescription", testNilDescription),
        ("testStringDescription", testStringDescription),
        ("testUIntDescription", testUIntDescription),
    ]
}

extension EncodeArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodeArrayTests = [
        ("testEncodeBoolArray", testEncodeBoolArray),
        ("testEncodeInt16Array", testEncodeInt16Array),
        ("testEncodeInt32Array", testEncodeInt32Array),
        ("testEncodeInt64Array", testEncodeInt64Array),
        ("testEncodeInt8Array", testEncodeInt8Array),
        ("testEncodeIntArray", testEncodeIntArray),
        ("testEncodeUInt16Array", testEncodeUInt16Array),
        ("testEncodeUInt32Array", testEncodeUInt32Array),
        ("testEncodeUInt64Array", testEncodeUInt64Array),
        ("testEncodeUInt8Array", testEncodeUInt8Array),
        ("testEncodeUIntArray", testEncodeUIntArray),
    ]
}

extension EqualityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EqualityTests = [
        ("testArrayEquality", testArrayEquality),
        ("testBinaryEquality", testBinaryEquality),
        ("testBoolEquality", testBoolEquality),
        ("testExtendedEquality", testExtendedEquality),
        ("testFloatEquality", testFloatEquality),
        ("testIntEquality", testIntEquality),
        ("testMapEquality", testMapEquality),
        ("testNilEquality", testNilEquality),
        ("testStringEquality", testStringEquality),
        ("testUIntEquality", testUIntEquality),
    ]
}

extension ExtendedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtendedTests = [
        ("testDecodeExt16", testDecodeExt16),
        ("testDecodeExt32", testDecodeExt32),
        ("testDecodeExt8", testDecodeExt8),
        ("testDecodeFixExt1", testDecodeFixExt1),
        ("testDecodeFixExt16", testDecodeFixExt16),
        ("testDecodeFixExt2", testDecodeFixExt2),
        ("testDecodeFixExt4", testDecodeFixExt4),
        ("testDecodeFixExt8", testDecodeFixExt8),
        ("testEncodeExt16", testEncodeExt16),
        ("testEncodeExt32", testEncodeExt32),
        ("testEncodeExt8", testEncodeExt8),
        ("testEncodeFixExt1", testEncodeFixExt1),
        ("testEncodeFixExt16", testEncodeFixExt16),
        ("testEncodeFixExt2", testEncodeFixExt2),
        ("testEncodeFixExt4", testEncodeFixExt4),
        ("testEncodeFixExt8", testEncodeFixExt8),
    ]
}

extension FloatTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FloatTests = [
        ("testDecodeDouble", testDecodeDouble),
        ("testDecodeFloat", testDecodeFloat),
        ("testEncodeDouble", testEncodeDouble),
        ("testEncodeFloat", testEncodeFloat),
    ]
}

extension InitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InitTests = [
        ("testByteStream", testByteStream),
    ]
}

extension InsufficientDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InsufficientDataTests = [
        ("testArrayInsufficientData", testArrayInsufficientData),
        ("testBinaryInsufficientData", testBinaryInsufficientData),
        ("testExtendedInsufficientData", testExtendedInsufficientData),
        ("testFloatInsufficientData", testFloatInsufficientData),
        ("testIntegerInsufficientData", testIntegerInsufficientData),
        ("testInvalidData", testInvalidData),
        ("testMapInsufficientData", testMapInsufficientData),
        ("testStringInsufficientData", testStringInsufficientData),
    ]
}

extension IntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntegerTests = [
        ("testDecodeNegativeFixInt", testDecodeNegativeFixInt),
        ("testDecodeNegativeInt16", testDecodeNegativeInt16),
        ("testDecodeNegativeInt32", testDecodeNegativeInt32),
        ("testDecodeNegativeInt64", testDecodeNegativeInt64),
        ("testDecodeNegativeInt8", testDecodeNegativeInt8),
        ("testDecodePositiveFixInt", testDecodePositiveFixInt),
        ("testDecodeUInt16", testDecodeUInt16),
        ("testDecodeUInt32", testDecodeUInt32),
        ("testDecodeUInt64", testDecodeUInt64),
        ("testDecodeUInt8", testDecodeUInt8),
        ("testEncodeInt", testEncodeInt),
        ("testEncodeNegativeIntToFixInt", testEncodeNegativeIntToFixInt),
        ("testEncodePositiveIntToFixInt", testEncodePositiveIntToFixInt),
        ("testEncodeUInt", testEncodeUInt),
    ]
}

extension InvalidHeaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InvalidHeaderTests = [
        ("testArrayHeader", testArrayHeader),
        ("testBinaryHeader", testBinaryHeader),
        ("testExtendedHeader", testExtendedHeader),
        ("testMapHeader", testMapHeader),
        ("testStringHeader", testStringHeader),
    ]
}

extension KeyedDecodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedDecodingContainerTests = [
        ("testKeyedContainer", testKeyedContainer),
        ("testNestedKeyedContainer", testNestedKeyedContainer),
        ("testNestedUnkeyedContainer", testNestedUnkeyedContainer),
    ]
}

extension KeyedEncodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedEncodingContainerTests = [
        ("testKeyedContainer", testKeyedContainer),
        ("testNestedKeyedContainer", testNestedKeyedContainer),
        ("testNestedUnkeyedContainer", testNestedUnkeyedContainer),
    ]
}

extension LiteralConvertibleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LiteralConvertibleTests = [
        ("testArrayLiteralConvertible", testArrayLiteralConvertible),
        ("testBooleanLiteralConvertible", testBooleanLiteralConvertible),
        ("testDictionaryLiteralConvertible", testDictionaryLiteralConvertible),
        ("testFloatLiteralConvertible", testFloatLiteralConvertible),
        ("testNilLiteralConvertible", testNilLiteralConvertible),
        ("testSignedIntegerLiteralConvertible", testSignedIntegerLiteralConvertible),
        ("testStringLiteralConvertible", testStringLiteralConvertible),
        ("testUnsignedIntegerLiteralConvertible", testUnsignedIntegerLiteralConvertible),
    ]
}

extension ManualHeadersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ManualHeadersTests = [
        ("testDecodeArray", testDecodeArray),
        ("testDecodeMap", testDecodeMap),
        ("testEncodeArray", testEncodeArray),
        ("testEncodeMap", testEncodeMap),
    ]
}

extension MapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MapTests = [
        ("testDecodeFixMap", testDecodeFixMap),
        ("testDecodeMap16", testDecodeMap16),
        ("testDecodeMap32", testDecodeMap32),
        ("testEmptyMap", testEmptyMap),
        ("testEncodeFixMap", testEncodeFixMap),
        ("testEncodeMap16", testEncodeMap16),
        ("testEncodeMap32", testEncodeMap32),
        ("testFixMapSize", testFixMapSize),
    ]
}

extension MessagePackCodersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MessagePackCodersTests = [
        ("testDecodable", testDecodable),
        ("testEncodable", testEncodable),
    ]
}

extension MessagePackInitializableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MessagePackInitializableTests = [
        ("testArray", testArray),
        ("testArrayOfInt", testArrayOfInt),
        ("testArrayOfString", testArrayOfString),
        ("testBinary", testBinary),
        ("testDictionary", testDictionary),
        ("testExtended", testExtended),
    ]
}

extension NilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NilTests = [
        ("testDecodeNil", testDecodeNil),
        ("testEncodeNil", testEncodeNil),
        ("testHasValue", testHasValue),
    ]
}

extension StringEncodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringEncodingTests = [
        ("testASCIIString", testASCIIString),
        ("testEnglishString", testEnglishString),
        ("testJapaneseString", testJapaneseString),
        ("testRussianString", testRussianString),
        ("testSwedishString", testSwedishString),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testDecodeFixStr", testDecodeFixStr),
        ("testDecodeStr16", testDecodeStr16),
        ("testDecodeStr32", testDecodeStr32),
        ("testDecodeStr8", testDecodeStr8),
        ("testEncodeFixStr", testEncodeFixStr),
        ("testEncodeStr16", testEncodeStr16),
        ("testEncodeStr32", testEncodeStr32),
        ("testEncodeStr8", testEncodeStr8),
    ]
}

extension TimestampTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimestampTests = [
        ("testDecode12", testDecode12),
        ("testDecode4", testDecode4),
        ("testDecode8", testDecode8),
        ("testEncode12", testEncode12),
        ("testEncode4", testEncode4),
        ("testEncode8", testEncode8),
    ]
}

extension UnkeyedDecodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedDecodingContainerTests = [
        ("testNestedKeyedContainer", testNestedKeyedContainer),
        ("testNestedUnkeyedContainer", testNestedUnkeyedContainer),
        ("testUnkeyedContainer", testUnkeyedContainer),
    ]
}

extension UnkeyedEncodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedEncodingContainerTests = [
        ("testNestedKeyedContainer", testNestedKeyedContainer),
        ("testNestedUnkeyedContainer", testNestedUnkeyedContainer),
        ("testUnkeyedContainer", testUnkeyedContainer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccessorsTests.__allTests__AccessorsTests),
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(BinaryTests.__allTests__BinaryTests),
        testCase(BoolTests.__allTests__BoolTests),
        testCase(ConvenienceInitializersTests.__allTests__ConvenienceInitializersTests),
        testCase(DecodeTests.__allTests__DecodeTests),
        testCase(DescriptionTests.__allTests__DescriptionTests),
        testCase(EncodeArrayTests.__allTests__EncodeArrayTests),
        testCase(EqualityTests.__allTests__EqualityTests),
        testCase(ExtendedTests.__allTests__ExtendedTests),
        testCase(FloatTests.__allTests__FloatTests),
        testCase(InitTests.__allTests__InitTests),
        testCase(InsufficientDataTests.__allTests__InsufficientDataTests),
        testCase(IntegerTests.__allTests__IntegerTests),
        testCase(InvalidHeaderTests.__allTests__InvalidHeaderTests),
        testCase(KeyedDecodingContainerTests.__allTests__KeyedDecodingContainerTests),
        testCase(KeyedEncodingContainerTests.__allTests__KeyedEncodingContainerTests),
        testCase(LiteralConvertibleTests.__allTests__LiteralConvertibleTests),
        testCase(ManualHeadersTests.__allTests__ManualHeadersTests),
        testCase(MapTests.__allTests__MapTests),
        testCase(MessagePackCodersTests.__allTests__MessagePackCodersTests),
        testCase(MessagePackInitializableTests.__allTests__MessagePackInitializableTests),
        testCase(NilTests.__allTests__NilTests),
        testCase(StringEncodingTests.__allTests__StringEncodingTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(TimestampTests.__allTests__TimestampTests),
        testCase(UnkeyedDecodingContainerTests.__allTests__UnkeyedDecodingContainerTests),
        testCase(UnkeyedEncodingContainerTests.__allTests__UnkeyedEncodingContainerTests),
    ]
}
#endif
